namespace CoreErp.Api.Dtos;

public class ProductWithStockDto
{
    public int ProductId { get; set; }
    public string ProductCode { get; set; } = "";
    public string ProductName { get; set; } = "";
    public decimal UnitPrice { get; set; }
    public int UnitsPerBox { get; set; }
    public string UnitOfMeasure { get; set; } = "";
    public decimal QuantityOnHand { get; set; }
    public decimal ReorderLevel { get; set; }
    public bool IsLowStock { get; set; }
}

public class CreateProductRequest
{
    // ProductCode is no longer needed — auto-generated by the API
    public string ProductName { get; set; } = "";
    public decimal UnitPrice { get; set; }
    public int UnitsPerBox { get; set; } = 1;
    public string UnitOfMeasure { get; set; } = "Piece";
    public decimal InitialStock { get; set; } = 0;
    public decimal ReorderLevel { get; set; } = 5;
}

public class UpdateProductRequest
{
    public string ProductCode { get; set; } = "";
    public string ProductName { get; set; } = "";
    public decimal UnitPrice { get; set; }
    public int UnitsPerBox { get; set; } = 1;
    public string UnitOfMeasure { get; set; } = "Piece";
    public decimal ReorderLevel { get; set; } = 5;
}

public class AdjustStockRequest
{
    public int ProductId { get; set; }
    public decimal QuantityDelta { get; set; }
    public decimal ReorderLevel { get; set; }
}